# Supervised Learning Model Evaluation Lab

Complete the exercises below to solidify your knowledge and understanding of supervised learning model evaluation.

In [1]:
import pandas as pd
%pip install sklearn

DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Note: you may need to restart the kernel to use updated packages.


## Regression Model Evaluation.

In [2]:
from sklearn.datasets import load_boston

data = load_boston()

X = pd.DataFrame(data["data"], columns=data["feature_names"])
y = pd.DataFrame(data["target"], columns=['MEDV'])

data = pd.concat([X, y], axis=1)

/opt/homebrew/lib/python3.9/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (i

In [3]:
X

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  
0       15.3  396.90   4.98  
1       17.8  396.90   9.14  
2       17.8  392.83   4.03  
3       18.7  394.63   2.94  
4       18.7  396.90   5.33  
..       ...     ...    ...  
501     21.0  391.99   9.67  
502     21.0  396.90   9.08  
503     21.0  396.90   5.64  
504     21.0  393.45   6.48  
505     21.0  396.90   7.88  

[506 rows x 13 columns]

In [4]:
y

MEDV
0    24.0
1    21.6
2    34.7
3    33.4
4    36.2
..    ...
501  22.4
502  20.6
503  23.9
504  22.0
505  11.9

[506 rows x 1 columns]

## 1. Split this data set into training (80%) and testing (20%) sets.

The `MEDV` field represents the median value of owner-occupied homes (in $1000's) and is the target variable that we will want to predict.

In [5]:
from sklearn.model_selection import train_test_split as tts 

X_train, X_test, y_train, y_test=tts(X, y)


X_train.shape, X_test.shape, y_train.shape, y_test.shape


((379, 13), (127, 13), (379, 1), (127, 1))

## 2. Train a `LinearRegression` model on this data set and generate predictions on both the training and the testing set.

In [6]:
from sklearn.linear_model import LinearRegression as LinReg


In [7]:
linreg=LinReg()

In [8]:
linreg.fit(X_train, y_train)

LinearRegression()

In [9]:
y_pred = linreg.predict(X_test)

y_pred[:10]

array([[16.96982707],
       [24.89663181],
       [20.22300005],
       [22.71234244],
       [13.42713752],
       [23.03548418],
       [22.83971262],
       [20.79434326],
       [ 8.1351374 ],
       [20.43469694]])

In [10]:
y_pred.shape

(127, 1)

In [11]:
linreg_t=LinReg()
linreg_t.fit(X_test, y_test)
y_pred_t = linreg_t.predict(X_train)
y_pred_t[:10]

array([[21.78236155],
       [21.84406124],
       [23.84046135],
       [25.23819727],
       [ 5.86257488],
       [24.80133219],
       [18.51930301],
       [24.385501  ],
       [20.71534308],
       [32.15169321]])

## 3. Calculate and print R-squared for both the training and the testing set.

In [12]:
from sklearn.metrics import mean_squared_error as mse  # error cuadratico medio

print(mse(y_test, y_pred))

print(mse(y_train, y_pred_t))


20.56981902227024
27.018182728505383


## 4. Calculate and print mean squared error for both the training and the testing set.

In [13]:
print(mse(y_test, y_pred, squared=False))
print(mse(y_train,y_pred_t, squared=False))

4.535396236523359
5.19790176210607


## 5. Calculate and print mean absolute error for both the training and the testing set.

In [14]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test, y_pred)

3.3264837986218603

## Classification Model Evaluation

In [15]:
from sklearn.datasets import load_iris

data = load_iris()

X = pd.DataFrame(data["data"], columns=data["feature_names"])
y = pd.DataFrame(data["target"], columns=["class"])

data = pd.concat([X, y], axis=1)

## 6. Split this data set into training (80%) and testing (20%) sets.

The `class` field represents the type of flower and is the target variable that we will want to predict.

In [16]:
X_train, X_test, y_train, y_test=tts(X, y)


X_train.shape, X_test.shape, y_train.shape, y_test.shape

((112, 4), (38, 4), (112, 1), (38, 1))

## 7. Train a `LogisticRegression` model on this data set and generate predictions on both the training and the testing set.

In [17]:
from sklearn.linear_model import LogisticRegression            # logistic regression model   
logreg=LogisticRegression(max_iter=2000)

In [18]:
logreg.fit(X_train, y_train)


/opt/homebrew/lib/python3.9/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(max_iter=2000)

In [19]:
y_pred=logreg.predict(X_test)
y_pred[:10]


array([0, 2, 1, 0, 0, 1, 0, 0, 1, 1])

In [21]:
logreg_t=LogisticRegression(max_iter=2000)

logreg_t.fit(X_test, y_test)
y_pred_t=logreg.predict(X_train)

y_pred_t[:10]

/opt/homebrew/lib/python3.9/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([1, 0, 1, 2, 0, 2, 0, 2, 2, 1])

## 8. Calculate and print the accuracy score for both the training and the testing set.

In [23]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))
print(accuracy_score(y_train, y_pred_t))

0.8947368421052632
0.9910714285714286


## 9. Calculate and print the balanced accuracy score for both the training and the testing set.

In [31]:
#sklearn.metrics.balanced_accuracy_score(y_true, y_pred, *, sample_weight=None, adjusted=False)
from sklearn.metrics import balanced_accuracy_score
print(balanced_accuracy_score(y_test, y_pred))
print(balanced_accuracy_score(y_train, y_pred_t))

0.8653846153846154
0.990990990990991


## 10. Calculate and print the precision score for both the training and the testing set.

In [35]:
from sklearn.metrics import precision_score
print(precision_score(y_test, y_pred, average='macro'))
print(precision_score(y_train, y_pred_t,average='macro'))


0.8653846153846154
0.9922480620155039


## 11. Calculate and print the recall score for both the training and the testing set.

In [37]:
from sklearn.metrics import recall_score
print(recall_score(y_test, y_pred, average='macro'))
print(recall_score(y_train, y_pred_t,average='macro'))

0.8653846153846154
0.990990990990991


## 12. Calculate and print the F1 score for both the training and the testing set.

In [38]:
from sklearn.metrics import f1_score
print(f1_score(y_test, y_pred, average='macro'))
print(f1_score(y_train, y_pred_t,average='macro'))

0.8653846153846154
0.9915122213268869


## 13. Generate confusion matrices for both the training and the testing set.

In [40]:
from sklearn.metrics import confusion_matrix as cm

print(cm(y_test, y_pred))
print(cm(y_train, y_pred_t))

[[17  0  0]
 [ 0 11  2]
 [ 0  2  6]]
[[33  0  0]
 [ 0 36  1]
 [ 0  0 42]]


## Bonus: For each of the data sets in this lab, try training with some of the other models you have learned about, recalculate the evaluation metrics, and compare to determine which models perform best on each data set.