# Supervised Learning Model Evaluation Lab

Complete the exercises below to solidify your knowledge and understanding of supervised learning model evaluation.

In [1]:
import pandas as pd

## Regression Model Evaluation

In [2]:
from sklearn.datasets import load_boston

data = load_boston()

X = pd.DataFrame(data["data"], columns=data["feature_names"])
y = pd.DataFrame(data["target"], columns=['MEDV'])

data = pd.concat([X, y], axis=1)

C:\Users\jgcha\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the

## 1. Split this data set into training (80%) and testing (20%) sets.

The `MEDV` field represents the median value of owner-occupied homes (in $1000's) and is the target variable that we will want to predict.

In [3]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

## 2. Train a `LinearRegression` model on this data set and generate predictions on both the training and the testing set.

In [4]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression()
lr.fit(X_train, y_train)
y_pred_train = lr.predict(X_train)
y_pred_test = lr.predict(X_test)

## 3. Calculate and print R-squared for both the training and the testing set.

In [10]:
from sklearn.metrics import r2_score as r2

print(f'R2 for training set: {r2(y_train, y_pred_train)}')
print(f'R2 for test set: {r2(y_test, y_pred_test)}')

R2 for training set: 0.7508856358979673
R2 for test set: 0.6687594935356326


## 4. Calculate and print mean squared error for both the training and the testing set.

In [12]:
from sklearn.metrics import mean_squared_error as mse 

print(f'MSE for training set: {mse(y_train, y_pred_train)}')
print(f'MSE for test set: {mse(y_test, y_pred_test)}')

MSE for training set: 21.641412753226312
MSE for test set: 24.291119474973478


## 5. Calculate and print mean absolute error for both the training and the testing set.

In [13]:
from sklearn.metrics import mean_absolute_error as mae 

print(f'MAE for training set: {mae(y_train, y_pred_train)}')
print(f'MAE for test set: {mae(y_test, y_pred_test)}')

MAE for training set: 3.314771626783221
MAE for test set: 3.1890919658878363


## Classification Model Evaluation

In [14]:
from sklearn.datasets import load_iris

data = load_iris()

X = pd.DataFrame(data["data"], columns=data["feature_names"])
y = pd.DataFrame(data["target"], columns=["class"])

data = pd.concat([X, y], axis=1)

## 6. Split this data set into training (80%) and testing (20%) sets.

The `class` field represents the type of flower and is the target variable that we will want to predict.

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

## 7. Train a `LogisticRegression` model on this data set and generate predictions on both the training and the testing set.

In [18]:
# Import LogisticRegression from Sklearn
from sklearn.linear_model import LogisticRegression

logreg = LogisticRegression()
logreg.fit(X_train, y_train)

y_pred_train = logreg.predict(X_train)
y_pred_test = logreg.predict(X_test)


C:\Users\jgcha\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\jgcha\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


## 8. Calculate and print the accuracy score for both the training and the testing set.

In [19]:
from sklearn.metrics import accuracy_score 

print(f'Accuracy for training set: {accuracy_score(y_train, y_pred_train)}')
print(f'Accuracy for test set: {accuracy_score(y_test, y_pred_test)}')

Accuracy for training set: 0.975
Accuracy for test set: 1.0


## 9. Calculate and print the balanced accuracy score for both the training and the testing set.

In [25]:
# Import balanced accuracy score

from sklearn.metrics import balanced_accuracy_score as bacc

print(f'Balanced accuracy for training set: {bacc(y_train, y_pred_train)}')
print(f'Balanced accuracy for test set: {bacc(y_test, y_pred_test)}')

Balanced accuracy for training set: 0.975609756097561
Balanced accuracy for test set: 1.0


## 10. Calculate and print the precision score for both the training and the testing set.

In [22]:
# Import precision
from sklearn.metrics import precision_score

print(f'Precision for training set: {precision_score(y_train, y_pred_train, average="macro")}')
print(f'Precision for test set: {precision_score(y_test, y_pred_test, average="macro")}')

Precision for training set: 0.9761904761904763
Precision for test set: 1.0


## 11. Calculate and print the recall score for both the training and the testing set.

In [23]:
# Import recall
from sklearn.metrics import recall_score

print(f'Recall for training set: {recall_score(y_train, y_pred_train, average="macro")}')
print(f'Recall for test set: {recall_score(y_test, y_pred_test, average="macro")}')

Recall for training set: 0.975609756097561
Recall for test set: 1.0


## 12. Calculate and print the F1 score for both the training and the testing set.

In [24]:
# Import F score 
from sklearn.metrics import f1_score

print(f'F1 score for training set: {f1_score(y_train, y_pred_train, average="macro")}')
print(f'F1 score for test set: {f1_score(y_test, y_pred_test, average="macro")}')

F1 score for training set: 0.9749960931395533
F1 score for test set: 1.0


## 13. Generate confusion matrices for both the training and the testing set.

In [27]:
# Import confusion matrix

from sklearn.metrics import confusion_matrix

print(f"""Confusion matrix for training set: 
{confusion_matrix(y_train, y_pred_train)}""")
print(f"""Confusion matrix for test set: 
{confusion_matrix(y_test, y_pred_test)}""")

Confusion matrix for training set: 
[[40  0  0]
 [ 0 38  3]
 [ 0  0 39]]
Confusion matrix for test set: 
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


## Bonus: For each of the data sets in this lab, try training with some of the other models you have learned about, recalculate the evaluation metrics, and compare to determine which models perform best on each data set.